sonar.projectKey=DanElement_Boutique_Database
sonar.projectName=DanElement Boutique - Seguridad de Base de Datos
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=squ_5ab15828892e8467acb5120c8f940d56ff962913
sonar.sources=src/config, src/controllers, src/services
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**