sonar.projectKey=DanElement_Boutique_Backend
sonar.projectName=DanElement Boutique - Backend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=squ_5ab15828892e8467acb5120c8f940d56ff962913
sonar.sources=src
sonar.exclusions=**/node_modules/**
sonar.sourceEncoding=UTF-8